# DEPLOY IMAGE
FROM cypress/browsers:node14.19.0-chrome100-ff99-edge

COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin/

COPY meteor/bundle /opt/core
COPY meteor/docker-entrypoint.sh /opt
WORKDIR /opt/core/
CMD ["/opt/docker-entrypoint.sh"]
