name: Other Issue 🔧
description: Use this for other issues
title: "Other: [Short description of the issue]"
labels:
  - Other

body:
  - type: markdown
    attributes:
      value: |
        Before you post, be sure to read our Contribution guidelines:
        https://nrkno.github.io/sofie-core/docs/for-developers/contribution-guidelines

  - type: textarea
    attributes:
      label: About me
      description: Tell us who / which organization you are representing, and how the Sofie team will be able to contact you.
      placeholder: Example "This RFC is posted on behalf of the NRK."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue
      description: Describe the issue below
    validations:
      required: true
