name: Request for Comments ❗
description: Use this to initiate a discussion about a new feature or a larger change
title: "RFC: [Short description of the feature/change]"
labels:
  - RFC
  - Contribution

body:
  - type: markdown
    attributes:
      value: |
        Before you post, be sure to read our Contribution guidelines:
        https://nrkno.github.io/sofie-core/docs/for-developers/contribution-guidelines

  - type: textarea
    attributes:
      label: About me
      description: Tell us who / which organization you are representing, and how the Sofie team will be able to contact you.
      placeholder: Example "This RFC is posted on behalf of the NRK."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: "Please write some background information here, such as: What is your use case? What problem are you trying to solve?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposal
      description: Please describe your proposal here
    validations:
      required: true

  - type: textarea
    attributes:
      label: Process
      description: Please don't touch this section, the Sofie team will update this as the RFC progresses.
      value: |
        The Sofie Team will evaluate this RFC and open up a discussion about it, usually within a week.
        - [x] RFC created
        - [ ] Sofie Team has evaluated the RFC
        - [ ] A workshop has been planned
        - [ ] RFC has been discussed in a workshop
        - [ ] A conclusion has been reached, see comments in thread
